apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: openfaas-flux
  namespace: flux-system
spec:
  interval: 5m
  url: https://openfaas.github.io/faas-netes
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openfaas
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: openfaas
  chart:
    spec:
      chart: openfaas
      version: 14.2.0
      sourceRef:
        kind: HelmRepository
        name: openfaas-flux
        namespace: flux-system
  values:
    generateBasicAuth: true
    functionNamespace: openfaas-fn
    installCRDs: true 
