apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: functions
  namespace: flux-system
spec:
  interval: 2m
  path: ../functions
  prune: true
  sourceRef:
    kind: GitRepository
    name: openfaas-flux
    namespace: flux-system
  validation: client